@startuml
'https://plantuml.com/object-diagram

object simulator

package stsplugin {
    object wegeliste
        wegeliste : konstant

    object bahnsteigliste
        bahnsteigliste : konstant

    object zugliste
        zugliste : variabel

}

package stsgraph {
    object signalgraph
        signalgraph : signale
        signalgraph : weichen
        signalgraph : einfahrten
        signalgraph : ausfahrten
        signalgraph : bahnsteige
        signalgraph : haltepunkte

    object bahnsteiggraph
        bahnsteiggraph : bahnsteige
        bahnsteiggraph : bahnhofteile

    object zuggraph
        zuggraph : zuege
        zuggraph : folgezuege
        zuggraph : stammzuege

    object zielgraph
        zielgraph : fahrplanziele
        zielgraph : trassen
}


object konfiguration
konfiguration : anschluesse
konfiguration : bahnhoefe
konfiguration : strecken



object auswertung

package anlage {
object bahnhofgraph
bahnhofgraph : bahnhoefe
bahnhofgraph : anschluesse
bahnhofgraph : relationen

object anschlussgruppen
object bahnsteiggruppen

object strecken
strecken : bahnhoefe
strecken : anschluesse
}

simulator --> zugliste
simulator --> wegeliste
simulator --> bahnsteigliste

wegeliste --> signalgraph : original-graph
signalgraph --> anschlussgruppen : auto-gruppen

bahnsteigliste --> bahnsteiggraph : original-graph
bahnsteiggraph --> bahnsteiggruppen : auto-gruppen

zugliste --> zuggraph : original-graph
zugliste --> zielgraph : original-graph

zielgraph --> bahnhofgraph : fahrzeiten
bahnsteiggruppen --> bahnhofgraph : bahnhoefe
anschlussgruppen --> bahnhofgraph : anschluesse

signalgraph --> strecken : relationen
signalgraph --> bahnhofgraph : relationen
bahnsteiggruppen --> strecken : bahnhoefe
anschlussgruppen --> strecken : anschluesse

konfiguration --> bahnsteiggruppen
konfiguration --> anschlussgruppen
konfiguration --> strecken

auswertung --> bahnhofgraph : fahrzeiten
'strecken --> bahnhofgraph : relationen

@enduml
