# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'anschlussmatrix.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QComboBox, QFrame,
    QGroupBox, QHBoxLayout, QHeaderView, QLabel,
    QMainWindow, QSizePolicy, QSpinBox, QSplitter,
    QStackedWidget, QTableView, QToolBar, QVBoxLayout,
    QWidget)
import stskit.qt.resources_rc

class Ui_AnschlussmatrixWindow(object):
    def setupUi(self, AnschlussmatrixWindow):
        if not AnschlussmatrixWindow.objectName():
            AnschlussmatrixWindow.setObjectName(u"AnschlussmatrixWindow")
        AnschlussmatrixWindow.resize(800, 600)
        self.actionSetup = QAction(AnschlussmatrixWindow)
        self.actionSetup.setObjectName(u"actionSetup")
        icon = QIcon()
        icon.addFile(u":/equalizer.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon.addFile(u":/equalizer-dis.png", QSize(), QIcon.Mode.Disabled, QIcon.State.Off)
        self.actionSetup.setIcon(icon)
        self.actionAnzeige = QAction(AnschlussmatrixWindow)
        self.actionAnzeige.setObjectName(u"actionAnzeige")
        icon1 = QIcon()
        icon1.addFile(u":/slots.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon1.addFile(u":/slots-dis.png", QSize(), QIcon.Mode.Disabled, QIcon.State.Off)
        self.actionAnzeige.setIcon(icon1)
        self.actionPlusEins = QAction(AnschlussmatrixWindow)
        self.actionPlusEins.setObjectName(u"actionPlusEins")
        icon2 = QIcon()
        icon2.addFile(u":/clock--plus.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionPlusEins.setIcon(icon2)
        self.actionMinusEins = QAction(AnschlussmatrixWindow)
        self.actionMinusEins.setObjectName(u"actionMinusEins")
        icon3 = QIcon()
        icon3.addFile(u":/clock--minus.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionMinusEins.setIcon(icon3)
        self.actionFix = QAction(AnschlussmatrixWindow)
        self.actionFix.setObjectName(u"actionFix")
        icon4 = QIcon()
        icon4.addFile(u":/clock--pencil.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionFix.setIcon(icon4)
        self.actionLoeschen = QAction(AnschlussmatrixWindow)
        self.actionLoeschen.setObjectName(u"actionLoeschen")
        icon5 = QIcon()
        icon5.addFile(u":/chain--return.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionLoeschen.setIcon(icon5)
        self.actionAnkunftAbwarten = QAction(AnschlussmatrixWindow)
        self.actionAnkunftAbwarten.setObjectName(u"actionAnkunftAbwarten")
        icon6 = QIcon()
        icon6.addFile(u":/chain--arrow-in.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionAnkunftAbwarten.setIcon(icon6)
        self.actionAbfahrtAbwarten = QAction(AnschlussmatrixWindow)
        self.actionAbfahrtAbwarten.setObjectName(u"actionAbfahrtAbwarten")
        icon7 = QIcon()
        icon7.addFile(u":/chain--arrow.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionAbfahrtAbwarten.setIcon(icon7)
        self.actionWarnungSetzen = QAction(AnschlussmatrixWindow)
        self.actionWarnungSetzen.setObjectName(u"actionWarnungSetzen")
        icon8 = QIcon()
        icon8.addFile(u":/flag.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionWarnungSetzen.setIcon(icon8)
        self.actionWarnungIgnorieren = QAction(AnschlussmatrixWindow)
        self.actionWarnungIgnorieren.setObjectName(u"actionWarnungIgnorieren")
        icon9 = QIcon()
        icon9.addFile(u":/flag-green.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionWarnungIgnorieren.setIcon(icon9)
        self.actionWarnungReset = QAction(AnschlussmatrixWindow)
        self.actionWarnungReset.setObjectName(u"actionWarnungReset")
        icon10 = QIcon()
        icon10.addFile(u":/flag-white.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionWarnungReset.setIcon(icon10)
        self.actionAnschlussAufgeben = QAction(AnschlussmatrixWindow)
        self.actionAnschlussAufgeben.setObjectName(u"actionAnschlussAufgeben")
        icon11 = QIcon()
        icon11.addFile(u":/chain--cross.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionAnschlussAufgeben.setIcon(icon11)
        self.actionZugAusblenden = QAction(AnschlussmatrixWindow)
        self.actionZugAusblenden.setObjectName(u"actionZugAusblenden")
        icon12 = QIcon()
        icon12.addFile(u":/train--minus.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionZugAusblenden.setIcon(icon12)
        self.actionZugEinblenden = QAction(AnschlussmatrixWindow)
        self.actionZugEinblenden.setObjectName(u"actionZugEinblenden")
        icon13 = QIcon()
        icon13.addFile(u":/train--return.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionZugEinblenden.setIcon(icon13)
        self.centralwidget = QWidget(AnschlussmatrixWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.settings_page = QWidget()
        self.settings_page.setObjectName(u"settings_page")
        self.verticalLayout_2 = QVBoxLayout(self.settings_page)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.allgemein_group = QGroupBox(self.settings_page)
        self.allgemein_group.setObjectName(u"allgemein_group")
        self.verticalLayout_3 = QVBoxLayout(self.allgemein_group)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.bahnhofLabel = QLabel(self.allgemein_group)
        self.bahnhofLabel.setObjectName(u"bahnhofLabel")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bahnhofLabel.sizePolicy().hasHeightForWidth())
        self.bahnhofLabel.setSizePolicy(sizePolicy)

        self.verticalLayout_3.addWidget(self.bahnhofLabel)

        self.bahnhofBox = QComboBox(self.allgemein_group)
        self.bahnhofBox.setObjectName(u"bahnhofBox")
        sizePolicy.setHeightForWidth(self.bahnhofBox.sizePolicy().hasHeightForWidth())
        self.bahnhofBox.setSizePolicy(sizePolicy)
        self.bahnhofBox.setMinimumSize(QSize(120, 0))
        self.bahnhofBox.setSizeAdjustPolicy(QComboBox.AdjustToContents)

        self.verticalLayout_3.addWidget(self.bahnhofBox)

        self.umsteigezeitLabel = QLabel(self.allgemein_group)
        self.umsteigezeitLabel.setObjectName(u"umsteigezeitLabel")
        sizePolicy.setHeightForWidth(self.umsteigezeitLabel.sizePolicy().hasHeightForWidth())
        self.umsteigezeitLabel.setSizePolicy(sizePolicy)

        self.verticalLayout_3.addWidget(self.umsteigezeitLabel)

        self.umsteigezeitSpin = QSpinBox(self.allgemein_group)
        self.umsteigezeitSpin.setObjectName(u"umsteigezeitSpin")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.umsteigezeitSpin.sizePolicy().hasHeightForWidth())
        self.umsteigezeitSpin.setSizePolicy(sizePolicy1)
        self.umsteigezeitSpin.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.umsteigezeitSpin.setValue(2)

        self.verticalLayout_3.addWidget(self.umsteigezeitSpin)

        self.anschlusszeitLabel = QLabel(self.allgemein_group)
        self.anschlusszeitLabel.setObjectName(u"anschlusszeitLabel")
        sizePolicy.setHeightForWidth(self.anschlusszeitLabel.sizePolicy().hasHeightForWidth())
        self.anschlusszeitLabel.setSizePolicy(sizePolicy)

        self.verticalLayout_3.addWidget(self.anschlusszeitLabel)

        self.anschlusszeitSpin = QSpinBox(self.allgemein_group)
        self.anschlusszeitSpin.setObjectName(u"anschlusszeitSpin")
        sizePolicy1.setHeightForWidth(self.anschlusszeitSpin.sizePolicy().hasHeightForWidth())
        self.anschlusszeitSpin.setSizePolicy(sizePolicy1)
        self.anschlusszeitSpin.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.anschlusszeitSpin.setValue(15)

        self.verticalLayout_3.addWidget(self.anschlusszeitSpin)

        self.allgemein_spacer_widget = QWidget(self.allgemein_group)
        self.allgemein_spacer_widget.setObjectName(u"allgemein_spacer_widget")

        self.verticalLayout_3.addWidget(self.allgemein_spacer_widget)


        self.horizontalLayout_2.addWidget(self.allgemein_group)

        self.ankunft_group = QGroupBox(self.settings_page)
        self.ankunft_group.setObjectName(u"ankunft_group")
        self.verticalLayout_4 = QVBoxLayout(self.ankunft_group)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.ankunft_filter_label = QLabel(self.ankunft_group)
        self.ankunft_filter_label.setObjectName(u"ankunft_filter_label")

        self.verticalLayout_4.addWidget(self.ankunft_filter_label)

        self.ankunft_filter_view = QTableView(self.ankunft_group)
        self.ankunft_filter_view.setObjectName(u"ankunft_filter_view")
        self.ankunft_filter_view.setAlternatingRowColors(True)
        self.ankunft_filter_view.setSelectionMode(QAbstractItemView.SingleSelection)
        self.ankunft_filter_view.setSelectionBehavior(QAbstractItemView.SelectRows)

        self.verticalLayout_4.addWidget(self.ankunft_filter_view)

        self.ankunft_filter_label_2 = QLabel(self.ankunft_group)
        self.ankunft_filter_label_2.setObjectName(u"ankunft_filter_label_2")

        self.verticalLayout_4.addWidget(self.ankunft_filter_label_2)

        self.ankunft_beschriftung_view = QTableView(self.ankunft_group)
        self.ankunft_beschriftung_view.setObjectName(u"ankunft_beschriftung_view")
        self.ankunft_beschriftung_view.setAlternatingRowColors(True)
        self.ankunft_beschriftung_view.setSelectionMode(QAbstractItemView.SingleSelection)
        self.ankunft_beschriftung_view.setSelectionBehavior(QAbstractItemView.SelectRows)

        self.verticalLayout_4.addWidget(self.ankunft_beschriftung_view)


        self.horizontalLayout_2.addWidget(self.ankunft_group)

        self.abfahrt_group = QGroupBox(self.settings_page)
        self.abfahrt_group.setObjectName(u"abfahrt_group")
        self.verticalLayout_5 = QVBoxLayout(self.abfahrt_group)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.abfahrt_filter_label = QLabel(self.abfahrt_group)
        self.abfahrt_filter_label.setObjectName(u"abfahrt_filter_label")

        self.verticalLayout_5.addWidget(self.abfahrt_filter_label)

        self.abfahrt_filter_view = QTableView(self.abfahrt_group)
        self.abfahrt_filter_view.setObjectName(u"abfahrt_filter_view")
        self.abfahrt_filter_view.setAlternatingRowColors(True)
        self.abfahrt_filter_view.setSelectionMode(QAbstractItemView.SingleSelection)
        self.abfahrt_filter_view.setSelectionBehavior(QAbstractItemView.SelectRows)

        self.verticalLayout_5.addWidget(self.abfahrt_filter_view)

        self.abfahrt_beschriftung_label = QLabel(self.abfahrt_group)
        self.abfahrt_beschriftung_label.setObjectName(u"abfahrt_beschriftung_label")

        self.verticalLayout_5.addWidget(self.abfahrt_beschriftung_label)

        self.abfahrt_beschriftung_view = QTableView(self.abfahrt_group)
        self.abfahrt_beschriftung_view.setObjectName(u"abfahrt_beschriftung_view")
        self.abfahrt_beschriftung_view.setAlternatingRowColors(True)
        self.abfahrt_beschriftung_view.setSelectionMode(QAbstractItemView.SingleSelection)
        self.abfahrt_beschriftung_view.setSelectionBehavior(QAbstractItemView.SelectRows)

        self.verticalLayout_5.addWidget(self.abfahrt_beschriftung_view)


        self.horizontalLayout_2.addWidget(self.abfahrt_group)


        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.stackedWidget.addWidget(self.settings_page)
        self.display_page = QWidget()
        self.display_page.setObjectName(u"display_page")
        self.horizontalLayout = QHBoxLayout(self.display_page)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.displaySplitter = QSplitter(self.display_page)
        self.displaySplitter.setObjectName(u"displaySplitter")
        self.displaySplitter.setOrientation(Qt.Vertical)
        self.grafikWidget = QWidget(self.displaySplitter)
        self.grafikWidget.setObjectName(u"grafikWidget")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.grafikWidget.sizePolicy().hasHeightForWidth())
        self.grafikWidget.setSizePolicy(sizePolicy2)
        self.displaySplitter.addWidget(self.grafikWidget)
        self.zuginfoLabel = QLabel(self.displaySplitter)
        self.zuginfoLabel.setObjectName(u"zuginfoLabel")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.zuginfoLabel.sizePolicy().hasHeightForWidth())
        self.zuginfoLabel.setSizePolicy(sizePolicy3)
        self.zuginfoLabel.setMaximumSize(QSize(16777215, 50))
        self.zuginfoLabel.setBaseSize(QSize(0, 0))
        self.zuginfoLabel.setFrameShape(QFrame.Box)
        self.zuginfoLabel.setFrameShadow(QFrame.Sunken)
        self.zuginfoLabel.setTextFormat(Qt.AutoText)
        self.zuginfoLabel.setTextInteractionFlags(Qt.TextSelectableByMouse)
        self.displaySplitter.addWidget(self.zuginfoLabel)

        self.horizontalLayout.addWidget(self.displaySplitter)

        self.stackedWidget.addWidget(self.display_page)

        self.verticalLayout.addWidget(self.stackedWidget)

        AnschlussmatrixWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QToolBar(AnschlussmatrixWindow)
        self.toolBar.setObjectName(u"toolBar")
        self.toolBar.setIconSize(QSize(16, 16))
        AnschlussmatrixWindow.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.toolBar)
#if QT_CONFIG(shortcut)
        self.bahnhofLabel.setBuddy(self.bahnhofBox)
        self.umsteigezeitLabel.setBuddy(self.umsteigezeitSpin)
        self.anschlusszeitLabel.setBuddy(self.anschlusszeitSpin)
#endif // QT_CONFIG(shortcut)

        self.toolBar.addAction(self.actionSetup)
        self.toolBar.addAction(self.actionAnzeige)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionZugAusblenden)
        self.toolBar.addAction(self.actionZugEinblenden)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPlusEins)
        self.toolBar.addAction(self.actionMinusEins)
        self.toolBar.addAction(self.actionFix)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionAnkunftAbwarten)
        self.toolBar.addAction(self.actionAbfahrtAbwarten)
        self.toolBar.addAction(self.actionAnschlussAufgeben)
        self.toolBar.addAction(self.actionLoeschen)

        self.retranslateUi(AnschlussmatrixWindow)

        self.stackedWidget.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(AnschlussmatrixWindow)
    # setupUi

    def retranslateUi(self, AnschlussmatrixWindow):
        AnschlussmatrixWindow.setWindowTitle(QCoreApplication.translate("AnschlussmatrixWindow", u"MainWindow", None))
        self.actionSetup.setText(QCoreApplication.translate("AnschlussmatrixWindow", u"Einstellungen", None))
#if QT_CONFIG(tooltip)
        self.actionSetup.setToolTip(QCoreApplication.translate("AnschlussmatrixWindow", u"Bahnhofauswahl (S)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionSetup.setShortcut(QCoreApplication.translate("AnschlussmatrixWindow", u"S", None))
#endif // QT_CONFIG(shortcut)
        self.actionAnzeige.setText(QCoreApplication.translate("AnschlussmatrixWindow", u"Grafik", None))
#if QT_CONFIG(tooltip)
        self.actionAnzeige.setToolTip(QCoreApplication.translate("AnschlussmatrixWindow", u"Grafik anzeigen (G)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionAnzeige.setShortcut(QCoreApplication.translate("AnschlussmatrixWindow", u"G", None))
#endif // QT_CONFIG(shortcut)
        self.actionPlusEins.setText(QCoreApplication.translate("AnschlussmatrixWindow", u"+1", None))
#if QT_CONFIG(tooltip)
        self.actionPlusEins.setToolTip(QCoreApplication.translate("AnschlussmatrixWindow", u"Versp\u00e4tung/Wartezeit um 1 Minute erh\u00f6hen (+)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionPlusEins.setShortcut(QCoreApplication.translate("AnschlussmatrixWindow", u"+", None))
#endif // QT_CONFIG(shortcut)
        self.actionMinusEins.setText(QCoreApplication.translate("AnschlussmatrixWindow", u"-1", None))
#if QT_CONFIG(tooltip)
        self.actionMinusEins.setToolTip(QCoreApplication.translate("AnschlussmatrixWindow", u"Versp\u00e4tung/Wartezeit um 1 Minute reduzieren (-)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionMinusEins.setShortcut(QCoreApplication.translate("AnschlussmatrixWindow", u"-", None))
#endif // QT_CONFIG(shortcut)
        self.actionFix.setText(QCoreApplication.translate("AnschlussmatrixWindow", u"Fix", None))
#if QT_CONFIG(tooltip)
        self.actionFix.setToolTip(QCoreApplication.translate("AnschlussmatrixWindow", u"Feste Versp\u00e4tung festlegen (V)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionFix.setShortcut(QCoreApplication.translate("AnschlussmatrixWindow", u"V", None))
#endif // QT_CONFIG(shortcut)
        self.actionLoeschen.setText(QCoreApplication.translate("AnschlussmatrixWindow", u"Verkn\u00fcpfung aufl\u00f6sen", None))
#if QT_CONFIG(tooltip)
        self.actionLoeschen.setToolTip(QCoreApplication.translate("AnschlussmatrixWindow", u"Verkn\u00fcpfung auf ausgew\u00e4hlten Anschl\u00fcssen aufl\u00f6sen (Del)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionLoeschen.setShortcut(QCoreApplication.translate("AnschlussmatrixWindow", u"Del", None))
#endif // QT_CONFIG(shortcut)
        self.actionAnkunftAbwarten.setText(QCoreApplication.translate("AnschlussmatrixWindow", u"Ankunft abwarten", None))
#if QT_CONFIG(tooltip)
        self.actionAnkunftAbwarten.setToolTip(QCoreApplication.translate("AnschlussmatrixWindow", u"Ankunft von Zubringer abwarten (K)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionAnkunftAbwarten.setShortcut(QCoreApplication.translate("AnschlussmatrixWindow", u"K", None))
#endif // QT_CONFIG(shortcut)
        self.actionAbfahrtAbwarten.setText(QCoreApplication.translate("AnschlussmatrixWindow", u"Abfahrt abwarten", None))
#if QT_CONFIG(tooltip)
        self.actionAbfahrtAbwarten.setToolTip(QCoreApplication.translate("AnschlussmatrixWindow", u"Abfahrt von Zubringer abwarten (F)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionAbfahrtAbwarten.setShortcut(QCoreApplication.translate("AnschlussmatrixWindow", u"F", None))
#endif // QT_CONFIG(shortcut)
        self.actionWarnungSetzen.setText(QCoreApplication.translate("AnschlussmatrixWindow", u"Warnung", None))
#if QT_CONFIG(tooltip)
        self.actionWarnungSetzen.setToolTip(QCoreApplication.translate("AnschlussmatrixWindow", u"Warnung setzen (W)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionWarnungSetzen.setShortcut(QCoreApplication.translate("AnschlussmatrixWindow", u"W", None))
#endif // QT_CONFIG(shortcut)
        self.actionWarnungIgnorieren.setText(QCoreApplication.translate("AnschlussmatrixWindow", u"Ignorieren", None))
#if QT_CONFIG(tooltip)
        self.actionWarnungIgnorieren.setToolTip(QCoreApplication.translate("AnschlussmatrixWindow", u"Warnung ignorieren (I)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionWarnungIgnorieren.setShortcut(QCoreApplication.translate("AnschlussmatrixWindow", u"I", None))
#endif // QT_CONFIG(shortcut)
        self.actionWarnungReset.setText(QCoreApplication.translate("AnschlussmatrixWindow", u"Reset", None))
#if QT_CONFIG(tooltip)
        self.actionWarnungReset.setToolTip(QCoreApplication.translate("AnschlussmatrixWindow", u"Warnung zur\u00fccksetzen (R)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionWarnungReset.setShortcut(QCoreApplication.translate("AnschlussmatrixWindow", u"R", None))
#endif // QT_CONFIG(shortcut)
        self.actionAnschlussAufgeben.setText(QCoreApplication.translate("AnschlussmatrixWindow", u"Anschluss aufgeben", None))
#if QT_CONFIG(tooltip)
        self.actionAnschlussAufgeben.setToolTip(QCoreApplication.translate("AnschlussmatrixWindow", u"Anschluss nicht abwarten (A)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionAnschlussAufgeben.setShortcut(QCoreApplication.translate("AnschlussmatrixWindow", u"A", None))
#endif // QT_CONFIG(shortcut)
        self.actionZugAusblenden.setText(QCoreApplication.translate("AnschlussmatrixWindow", u"Zug ausblenden", None))
#if QT_CONFIG(tooltip)
        self.actionZugAusblenden.setToolTip(QCoreApplication.translate("AnschlussmatrixWindow", u"Zug ausblenden (H)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionZugAusblenden.setShortcut(QCoreApplication.translate("AnschlussmatrixWindow", u"H", None))
#endif // QT_CONFIG(shortcut)
        self.actionZugEinblenden.setText(QCoreApplication.translate("AnschlussmatrixWindow", u"Zug einblenden", None))
#if QT_CONFIG(tooltip)
        self.actionZugEinblenden.setToolTip(QCoreApplication.translate("AnschlussmatrixWindow", u"Alle Z\u00fcge einblenden (Z)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionZugEinblenden.setShortcut(QCoreApplication.translate("AnschlussmatrixWindow", u"Z", None))
#endif // QT_CONFIG(shortcut)
        self.allgemein_group.setTitle(QCoreApplication.translate("AnschlussmatrixWindow", u"Allgemein", None))
        self.bahnhofLabel.setText(QCoreApplication.translate("AnschlussmatrixWindow", u"&Bahnhof", None))
        self.umsteigezeitLabel.setText(QCoreApplication.translate("AnschlussmatrixWindow", u"&Umsteigezeit", None))
        self.umsteigezeitSpin.setSuffix(QCoreApplication.translate("AnschlussmatrixWindow", u" Min.", None))
        self.anschlusszeitLabel.setText(QCoreApplication.translate("AnschlussmatrixWindow", u"&Anschlusszeit", None))
        self.anschlusszeitSpin.setSuffix(QCoreApplication.translate("AnschlussmatrixWindow", u" Min.", None))
        self.ankunft_group.setTitle(QCoreApplication.translate("AnschlussmatrixWindow", u"Ankommende Z\u00fcge", None))
        self.ankunft_filter_label.setText(QCoreApplication.translate("AnschlussmatrixWindow", u"Filter", None))
        self.ankunft_filter_label_2.setText(QCoreApplication.translate("AnschlussmatrixWindow", u"Beschriftung", None))
        self.abfahrt_group.setTitle(QCoreApplication.translate("AnschlussmatrixWindow", u"Abfahrende Z\u00fcge", None))
        self.abfahrt_filter_label.setText(QCoreApplication.translate("AnschlussmatrixWindow", u"Filter", None))
        self.abfahrt_beschriftung_label.setText(QCoreApplication.translate("AnschlussmatrixWindow", u"Beschriftung", None))
        self.zuginfoLabel.setText(QCoreApplication.translate("AnschlussmatrixWindow", u"Zuginfo: (keine Auswahl)", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("AnschlussmatrixWindow", u"toolBar", None))
    # retranslateUi

