# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'anschlussmatrix.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AnschlussmatrixWindow(object):
    def setupUi(self, AnschlussmatrixWindow):
        AnschlussmatrixWindow.setObjectName("AnschlussmatrixWindow")
        AnschlussmatrixWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(AnschlussmatrixWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.settings_page = QtWidgets.QWidget()
        self.settings_page.setObjectName("settings_page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.settings_page)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.allgemein_group = QtWidgets.QGroupBox(self.settings_page)
        self.allgemein_group.setObjectName("allgemein_group")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.allgemein_group)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.bahnhofLabel = QtWidgets.QLabel(self.allgemein_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bahnhofLabel.sizePolicy().hasHeightForWidth())
        self.bahnhofLabel.setSizePolicy(sizePolicy)
        self.bahnhofLabel.setObjectName("bahnhofLabel")
        self.verticalLayout_3.addWidget(self.bahnhofLabel)
        self.bahnhofBox = QtWidgets.QComboBox(self.allgemein_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bahnhofBox.sizePolicy().hasHeightForWidth())
        self.bahnhofBox.setSizePolicy(sizePolicy)
        self.bahnhofBox.setMinimumSize(QtCore.QSize(120, 0))
        self.bahnhofBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.bahnhofBox.setObjectName("bahnhofBox")
        self.verticalLayout_3.addWidget(self.bahnhofBox)
        self.umsteigezeitLabel = QtWidgets.QLabel(self.allgemein_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.umsteigezeitLabel.sizePolicy().hasHeightForWidth())
        self.umsteigezeitLabel.setSizePolicy(sizePolicy)
        self.umsteigezeitLabel.setObjectName("umsteigezeitLabel")
        self.verticalLayout_3.addWidget(self.umsteigezeitLabel)
        self.umsteigezeitSpin = QtWidgets.QSpinBox(self.allgemein_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.umsteigezeitSpin.sizePolicy().hasHeightForWidth())
        self.umsteigezeitSpin.setSizePolicy(sizePolicy)
        self.umsteigezeitSpin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.umsteigezeitSpin.setProperty("value", 2)
        self.umsteigezeitSpin.setObjectName("umsteigezeitSpin")
        self.verticalLayout_3.addWidget(self.umsteigezeitSpin)
        self.anschlusszeitLabel = QtWidgets.QLabel(self.allgemein_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.anschlusszeitLabel.sizePolicy().hasHeightForWidth())
        self.anschlusszeitLabel.setSizePolicy(sizePolicy)
        self.anschlusszeitLabel.setObjectName("anschlusszeitLabel")
        self.verticalLayout_3.addWidget(self.anschlusszeitLabel)
        self.anschlusszeitSpin = QtWidgets.QSpinBox(self.allgemein_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.anschlusszeitSpin.sizePolicy().hasHeightForWidth())
        self.anschlusszeitSpin.setSizePolicy(sizePolicy)
        self.anschlusszeitSpin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.anschlusszeitSpin.setProperty("value", 15)
        self.anschlusszeitSpin.setObjectName("anschlusszeitSpin")
        self.verticalLayout_3.addWidget(self.anschlusszeitSpin)
        self.allgemein_spacer_widget = QtWidgets.QWidget(self.allgemein_group)
        self.allgemein_spacer_widget.setObjectName("allgemein_spacer_widget")
        self.verticalLayout_3.addWidget(self.allgemein_spacer_widget)
        self.horizontalLayout_2.addWidget(self.allgemein_group)
        self.ankunft_group = QtWidgets.QGroupBox(self.settings_page)
        self.ankunft_group.setObjectName("ankunft_group")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.ankunft_group)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.ankunft_filter_label = QtWidgets.QLabel(self.ankunft_group)
        self.ankunft_filter_label.setObjectName("ankunft_filter_label")
        self.verticalLayout_4.addWidget(self.ankunft_filter_label)
        self.ankunft_filter_view = QtWidgets.QTableView(self.ankunft_group)
        self.ankunft_filter_view.setAlternatingRowColors(True)
        self.ankunft_filter_view.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.ankunft_filter_view.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.ankunft_filter_view.setObjectName("ankunft_filter_view")
        self.verticalLayout_4.addWidget(self.ankunft_filter_view)
        self.ankunft_filter_label_2 = QtWidgets.QLabel(self.ankunft_group)
        self.ankunft_filter_label_2.setObjectName("ankunft_filter_label_2")
        self.verticalLayout_4.addWidget(self.ankunft_filter_label_2)
        self.ankunft_beschriftung_view = QtWidgets.QTableView(self.ankunft_group)
        self.ankunft_beschriftung_view.setAlternatingRowColors(True)
        self.ankunft_beschriftung_view.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.ankunft_beschriftung_view.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.ankunft_beschriftung_view.setObjectName("ankunft_beschriftung_view")
        self.verticalLayout_4.addWidget(self.ankunft_beschriftung_view)
        self.horizontalLayout_2.addWidget(self.ankunft_group)
        self.abfahrt_group = QtWidgets.QGroupBox(self.settings_page)
        self.abfahrt_group.setObjectName("abfahrt_group")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.abfahrt_group)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.abfahrt_filter_label = QtWidgets.QLabel(self.abfahrt_group)
        self.abfahrt_filter_label.setObjectName("abfahrt_filter_label")
        self.verticalLayout_5.addWidget(self.abfahrt_filter_label)
        self.abfahrt_filter_view = QtWidgets.QTableView(self.abfahrt_group)
        self.abfahrt_filter_view.setAlternatingRowColors(True)
        self.abfahrt_filter_view.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.abfahrt_filter_view.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.abfahrt_filter_view.setObjectName("abfahrt_filter_view")
        self.verticalLayout_5.addWidget(self.abfahrt_filter_view)
        self.abfahrt_beschriftung_label = QtWidgets.QLabel(self.abfahrt_group)
        self.abfahrt_beschriftung_label.setObjectName("abfahrt_beschriftung_label")
        self.verticalLayout_5.addWidget(self.abfahrt_beschriftung_label)
        self.abfahrt_beschriftung_view = QtWidgets.QTableView(self.abfahrt_group)
        self.abfahrt_beschriftung_view.setAlternatingRowColors(True)
        self.abfahrt_beschriftung_view.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.abfahrt_beschriftung_view.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.abfahrt_beschriftung_view.setObjectName("abfahrt_beschriftung_view")
        self.verticalLayout_5.addWidget(self.abfahrt_beschriftung_view)
        self.horizontalLayout_2.addWidget(self.abfahrt_group)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.stackedWidget.addWidget(self.settings_page)
        self.display_page = QtWidgets.QWidget()
        self.display_page.setObjectName("display_page")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.display_page)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.displaySplitter = QtWidgets.QSplitter(self.display_page)
        self.displaySplitter.setOrientation(QtCore.Qt.Vertical)
        self.displaySplitter.setObjectName("displaySplitter")
        self.grafikWidget = QtWidgets.QWidget(self.displaySplitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grafikWidget.sizePolicy().hasHeightForWidth())
        self.grafikWidget.setSizePolicy(sizePolicy)
        self.grafikWidget.setObjectName("grafikWidget")
        self.zuginfoLabel = QtWidgets.QLabel(self.displaySplitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zuginfoLabel.sizePolicy().hasHeightForWidth())
        self.zuginfoLabel.setSizePolicy(sizePolicy)
        self.zuginfoLabel.setMaximumSize(QtCore.QSize(16777215, 50))
        self.zuginfoLabel.setBaseSize(QtCore.QSize(0, 0))
        self.zuginfoLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.zuginfoLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.zuginfoLabel.setTextFormat(QtCore.Qt.AutoText)
        self.zuginfoLabel.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.zuginfoLabel.setObjectName("zuginfoLabel")
        self.horizontalLayout.addWidget(self.displaySplitter)
        self.stackedWidget.addWidget(self.display_page)
        self.verticalLayout.addWidget(self.stackedWidget)
        AnschlussmatrixWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(AnschlussmatrixWindow)
        self.toolBar.setIconSize(QtCore.QSize(16, 16))
        self.toolBar.setObjectName("toolBar")
        AnschlussmatrixWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionSetup = QtWidgets.QAction(AnschlussmatrixWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/equalizer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/equalizer-dis.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.actionSetup.setIcon(icon)
        self.actionSetup.setObjectName("actionSetup")
        self.actionAnzeige = QtWidgets.QAction(AnschlussmatrixWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/slots.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/slots-dis.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.actionAnzeige.setIcon(icon1)
        self.actionAnzeige.setObjectName("actionAnzeige")
        self.actionPlusEins = QtWidgets.QAction(AnschlussmatrixWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/clock--plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPlusEins.setIcon(icon2)
        self.actionPlusEins.setObjectName("actionPlusEins")
        self.actionMinusEins = QtWidgets.QAction(AnschlussmatrixWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/clock--minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMinusEins.setIcon(icon3)
        self.actionMinusEins.setObjectName("actionMinusEins")
        self.actionFix = QtWidgets.QAction(AnschlussmatrixWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/clock--pencil.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFix.setIcon(icon4)
        self.actionFix.setObjectName("actionFix")
        self.actionLoeschen = QtWidgets.QAction(AnschlussmatrixWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/chain--return.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLoeschen.setIcon(icon5)
        self.actionLoeschen.setObjectName("actionLoeschen")
        self.actionAnkunftAbwarten = QtWidgets.QAction(AnschlussmatrixWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/chain--arrow-in.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAnkunftAbwarten.setIcon(icon6)
        self.actionAnkunftAbwarten.setObjectName("actionAnkunftAbwarten")
        self.actionAbfahrtAbwarten = QtWidgets.QAction(AnschlussmatrixWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/chain--arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbfahrtAbwarten.setIcon(icon7)
        self.actionAbfahrtAbwarten.setObjectName("actionAbfahrtAbwarten")
        self.actionWarnungSetzen = QtWidgets.QAction(AnschlussmatrixWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/flag.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionWarnungSetzen.setIcon(icon8)
        self.actionWarnungSetzen.setObjectName("actionWarnungSetzen")
        self.actionWarnungIgnorieren = QtWidgets.QAction(AnschlussmatrixWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/flag-green.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionWarnungIgnorieren.setIcon(icon9)
        self.actionWarnungIgnorieren.setObjectName("actionWarnungIgnorieren")
        self.actionWarnungReset = QtWidgets.QAction(AnschlussmatrixWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/flag-white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionWarnungReset.setIcon(icon10)
        self.actionWarnungReset.setObjectName("actionWarnungReset")
        self.actionAnschlussAufgeben = QtWidgets.QAction(AnschlussmatrixWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/chain--cross.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAnschlussAufgeben.setIcon(icon11)
        self.actionAnschlussAufgeben.setObjectName("actionAnschlussAufgeben")
        self.actionZugAusblenden = QtWidgets.QAction(AnschlussmatrixWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/train--minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZugAusblenden.setIcon(icon12)
        self.actionZugAusblenden.setObjectName("actionZugAusblenden")
        self.actionZugEinblenden = QtWidgets.QAction(AnschlussmatrixWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/train--return.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZugEinblenden.setIcon(icon13)
        self.actionZugEinblenden.setObjectName("actionZugEinblenden")
        self.toolBar.addAction(self.actionSetup)
        self.toolBar.addAction(self.actionAnzeige)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionZugAusblenden)
        self.toolBar.addAction(self.actionZugEinblenden)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPlusEins)
        self.toolBar.addAction(self.actionMinusEins)
        self.toolBar.addAction(self.actionFix)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionAnkunftAbwarten)
        self.toolBar.addAction(self.actionAbfahrtAbwarten)
        self.toolBar.addAction(self.actionAnschlussAufgeben)
        self.toolBar.addAction(self.actionLoeschen)
        self.bahnhofLabel.setBuddy(self.bahnhofBox)
        self.umsteigezeitLabel.setBuddy(self.umsteigezeitSpin)
        self.anschlusszeitLabel.setBuddy(self.anschlusszeitSpin)

        self.retranslateUi(AnschlussmatrixWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(AnschlussmatrixWindow)

    def retranslateUi(self, AnschlussmatrixWindow):
        _translate = QtCore.QCoreApplication.translate
        AnschlussmatrixWindow.setWindowTitle(_translate("AnschlussmatrixWindow", "MainWindow"))
        self.allgemein_group.setTitle(_translate("AnschlussmatrixWindow", "Allgemein"))
        self.bahnhofLabel.setText(_translate("AnschlussmatrixWindow", "&Bahnhof"))
        self.umsteigezeitLabel.setText(_translate("AnschlussmatrixWindow", "&Umsteigezeit"))
        self.umsteigezeitSpin.setSuffix(_translate("AnschlussmatrixWindow", " Min."))
        self.anschlusszeitLabel.setText(_translate("AnschlussmatrixWindow", "&Anschlusszeit"))
        self.anschlusszeitSpin.setSuffix(_translate("AnschlussmatrixWindow", " Min."))
        self.ankunft_group.setTitle(_translate("AnschlussmatrixWindow", "Ankommende Züge"))
        self.ankunft_filter_label.setText(_translate("AnschlussmatrixWindow", "Filter"))
        self.ankunft_filter_label_2.setText(_translate("AnschlussmatrixWindow", "Beschriftung"))
        self.abfahrt_group.setTitle(_translate("AnschlussmatrixWindow", "Abfahrende Züge"))
        self.abfahrt_filter_label.setText(_translate("AnschlussmatrixWindow", "Filter"))
        self.abfahrt_beschriftung_label.setText(_translate("AnschlussmatrixWindow", "Beschriftung"))
        self.zuginfoLabel.setText(_translate("AnschlussmatrixWindow", "Zuginfo: (keine Auswahl)"))
        self.toolBar.setWindowTitle(_translate("AnschlussmatrixWindow", "toolBar"))
        self.actionSetup.setText(_translate("AnschlussmatrixWindow", "Einstellungen"))
        self.actionSetup.setToolTip(_translate("AnschlussmatrixWindow", "Bahnhofauswahl (S)"))
        self.actionSetup.setShortcut(_translate("AnschlussmatrixWindow", "S"))
        self.actionAnzeige.setText(_translate("AnschlussmatrixWindow", "Grafik"))
        self.actionAnzeige.setToolTip(_translate("AnschlussmatrixWindow", "Grafik anzeigen (G)"))
        self.actionAnzeige.setShortcut(_translate("AnschlussmatrixWindow", "G"))
        self.actionPlusEins.setText(_translate("AnschlussmatrixWindow", "+1"))
        self.actionPlusEins.setToolTip(_translate("AnschlussmatrixWindow", "Verspätung/Wartezeit um 1 Minute erhöhen (+)"))
        self.actionPlusEins.setShortcut(_translate("AnschlussmatrixWindow", "+"))
        self.actionMinusEins.setText(_translate("AnschlussmatrixWindow", "-1"))
        self.actionMinusEins.setToolTip(_translate("AnschlussmatrixWindow", "Verspätung/Wartezeit um 1 Minute reduzieren (-)"))
        self.actionMinusEins.setShortcut(_translate("AnschlussmatrixWindow", "-"))
        self.actionFix.setText(_translate("AnschlussmatrixWindow", "Fix"))
        self.actionFix.setToolTip(_translate("AnschlussmatrixWindow", "Feste Verspätung festlegen (V)"))
        self.actionFix.setShortcut(_translate("AnschlussmatrixWindow", "V"))
        self.actionLoeschen.setText(_translate("AnschlussmatrixWindow", "Verknüpfung auflösen"))
        self.actionLoeschen.setToolTip(_translate("AnschlussmatrixWindow", "Verknüpfung auf ausgewählten Anschlüssen auflösen (Del)"))
        self.actionLoeschen.setShortcut(_translate("AnschlussmatrixWindow", "Del"))
        self.actionAnkunftAbwarten.setText(_translate("AnschlussmatrixWindow", "Ankunft abwarten"))
        self.actionAnkunftAbwarten.setToolTip(_translate("AnschlussmatrixWindow", "Ankunft von Zubringer abwarten (K)"))
        self.actionAnkunftAbwarten.setShortcut(_translate("AnschlussmatrixWindow", "K"))
        self.actionAbfahrtAbwarten.setText(_translate("AnschlussmatrixWindow", "Abfahrt abwarten"))
        self.actionAbfahrtAbwarten.setToolTip(_translate("AnschlussmatrixWindow", "Abfahrt von Zubringer abwarten (F)"))
        self.actionAbfahrtAbwarten.setShortcut(_translate("AnschlussmatrixWindow", "F"))
        self.actionWarnungSetzen.setText(_translate("AnschlussmatrixWindow", "Warnung"))
        self.actionWarnungSetzen.setToolTip(_translate("AnschlussmatrixWindow", "Warnung setzen (W)"))
        self.actionWarnungSetzen.setShortcut(_translate("AnschlussmatrixWindow", "W"))
        self.actionWarnungIgnorieren.setText(_translate("AnschlussmatrixWindow", "Ignorieren"))
        self.actionWarnungIgnorieren.setToolTip(_translate("AnschlussmatrixWindow", "Warnung ignorieren (I)"))
        self.actionWarnungIgnorieren.setShortcut(_translate("AnschlussmatrixWindow", "I"))
        self.actionWarnungReset.setText(_translate("AnschlussmatrixWindow", "Reset"))
        self.actionWarnungReset.setToolTip(_translate("AnschlussmatrixWindow", "Warnung zurücksetzen (R)"))
        self.actionWarnungReset.setShortcut(_translate("AnschlussmatrixWindow", "R"))
        self.actionAnschlussAufgeben.setText(_translate("AnschlussmatrixWindow", "Anschluss aufgeben"))
        self.actionAnschlussAufgeben.setToolTip(_translate("AnschlussmatrixWindow", "Anschluss nicht abwarten (A)"))
        self.actionAnschlussAufgeben.setShortcut(_translate("AnschlussmatrixWindow", "A"))
        self.actionZugAusblenden.setText(_translate("AnschlussmatrixWindow", "Zug ausblenden"))
        self.actionZugAusblenden.setToolTip(_translate("AnschlussmatrixWindow", "Zug ausblenden (H)"))
        self.actionZugAusblenden.setShortcut(_translate("AnschlussmatrixWindow", "H"))
        self.actionZugEinblenden.setText(_translate("AnschlussmatrixWindow", "Zug einblenden"))
        self.actionZugEinblenden.setToolTip(_translate("AnschlussmatrixWindow", "Alle Züge einblenden (Z)"))
        self.actionZugEinblenden.setShortcut(_translate("AnschlussmatrixWindow", "Z"))

import resources_rc
