# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gleisnetz.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GleisnetzWindow(object):
    def setupUi(self, GleisnetzWindow):
        GleisnetzWindow.setObjectName("GleisnetzWindow")
        GleisnetzWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(GleisnetzWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.signal_tab = QtWidgets.QWidget()
        self.signal_tab.setObjectName("signal_tab")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.signal_tab)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget_2 = QtWidgets.QWidget(self.signal_tab)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.splitter_2 = QtWidgets.QSplitter(self.widget_2)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.scrollArea = QtWidgets.QScrollArea(self.splitter_2)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.signal_graph_area = QtWidgets.QWidget()
        self.signal_graph_area.setGeometry(QtCore.QRect(0, 0, 68, 515))
        self.signal_graph_area.setObjectName("signal_graph_area")
        self.scrollArea.setWidget(self.signal_graph_area)
        self.signal_settings_frame = QtWidgets.QFrame(self.splitter_2)
        self.signal_settings_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.signal_settings_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.signal_settings_frame.setObjectName("signal_settings_frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.signal_settings_frame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.signal_weichen_check = QtWidgets.QCheckBox(self.signal_settings_frame)
        self.signal_weichen_check.setObjectName("signal_weichen_check")
        self.verticalLayout_5.addWidget(self.signal_weichen_check)
        self.signal_anschluss_check = QtWidgets.QCheckBox(self.signal_settings_frame)
        self.signal_anschluss_check.setObjectName("signal_anschluss_check")
        self.verticalLayout_5.addWidget(self.signal_anschluss_check)
        self.signal_bahnsteig_check = QtWidgets.QCheckBox(self.signal_settings_frame)
        self.signal_bahnsteig_check.setObjectName("signal_bahnsteig_check")
        self.verticalLayout_5.addWidget(self.signal_bahnsteig_check)
        self.signal_paar_check = QtWidgets.QCheckBox(self.signal_settings_frame)
        self.signal_paar_check.setObjectName("signal_paar_check")
        self.verticalLayout_5.addWidget(self.signal_paar_check)
        self.signal_zwischen_check = QtWidgets.QCheckBox(self.signal_settings_frame)
        self.signal_zwischen_check.setObjectName("signal_zwischen_check")
        self.verticalLayout_5.addWidget(self.signal_zwischen_check)
        self.signal_schleifen_check = QtWidgets.QCheckBox(self.signal_settings_frame)
        self.signal_schleifen_check.setObjectName("signal_schleifen_check")
        self.verticalLayout_5.addWidget(self.signal_schleifen_check)
        self.signal_nachbarn_check = QtWidgets.QCheckBox(self.signal_settings_frame)
        self.signal_nachbarn_check.setObjectName("signal_nachbarn_check")
        self.verticalLayout_5.addWidget(self.signal_nachbarn_check)
        self.signal_reserve1_check = QtWidgets.QCheckBox(self.signal_settings_frame)
        self.signal_reserve1_check.setObjectName("signal_reserve1_check")
        self.verticalLayout_5.addWidget(self.signal_reserve1_check)
        self.signal_aktualisieren_button = QtWidgets.QPushButton(self.signal_settings_frame)
        self.signal_aktualisieren_button.setObjectName("signal_aktualisieren_button")
        self.verticalLayout_5.addWidget(self.signal_aktualisieren_button)
        spacerItem = QtWidgets.QSpacerItem(20, 413, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.verticalLayout_6.addWidget(self.splitter_2)
        self.verticalLayout_7.addWidget(self.widget_2)
        self.tabWidget.addTab(self.signal_tab, "")
        self.bahnhof_tab = QtWidgets.QWidget()
        self.bahnhof_tab.setObjectName("bahnhof_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.bahnhof_tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(self.bahnhof_tab)
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.splitter = QtWidgets.QSplitter(self.widget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.splitter)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.bahnhof_graph_area = QtWidgets.QWidget()
        self.bahnhof_graph_area.setGeometry(QtCore.QRect(0, 0, 68, 515))
        self.bahnhof_graph_area.setObjectName("bahnhof_graph_area")
        self.scrollArea_2.setWidget(self.bahnhof_graph_area)
        self.bahnhof_settings_frame = QtWidgets.QFrame(self.splitter)
        self.bahnhof_settings_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bahnhof_settings_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.bahnhof_settings_frame.setObjectName("bahnhof_settings_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.bahnhof_settings_frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.bahnhof_leerverbindung_check = QtWidgets.QCheckBox(self.bahnhof_settings_frame)
        self.bahnhof_leerverbindung_check.setObjectName("bahnhof_leerverbindung_check")
        self.verticalLayout_3.addWidget(self.bahnhof_leerverbindung_check)
        self.bahnhof_check_1 = QtWidgets.QCheckBox(self.bahnhof_settings_frame)
        self.bahnhof_check_1.setObjectName("bahnhof_check_1")
        self.verticalLayout_3.addWidget(self.bahnhof_check_1)
        self.bahnhof_check_2 = QtWidgets.QCheckBox(self.bahnhof_settings_frame)
        self.bahnhof_check_2.setObjectName("bahnhof_check_2")
        self.verticalLayout_3.addWidget(self.bahnhof_check_2)
        self.bahnhof_check_3 = QtWidgets.QCheckBox(self.bahnhof_settings_frame)
        self.bahnhof_check_3.setObjectName("bahnhof_check_3")
        self.verticalLayout_3.addWidget(self.bahnhof_check_3)
        self.bahnhof_aktualisieren_button = QtWidgets.QPushButton(self.bahnhof_settings_frame)
        self.bahnhof_aktualisieren_button.setObjectName("bahnhof_aktualisieren_button")
        self.verticalLayout_3.addWidget(self.bahnhof_aktualisieren_button)
        spacerItem1 = QtWidgets.QSpacerItem(20, 364, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.verticalLayout_4.addWidget(self.splitter)
        self.verticalLayout_2.addWidget(self.widget)
        self.tabWidget.addTab(self.bahnhof_tab, "")
        self.linien_tab = QtWidgets.QWidget()
        self.linien_tab.setObjectName("linien_tab")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.linien_tab)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.widget_3 = QtWidgets.QWidget(self.linien_tab)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.splitter_3 = QtWidgets.QSplitter(self.widget_3)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.splitter_3)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.linien_graph_area = QtWidgets.QWidget()
        self.linien_graph_area.setGeometry(QtCore.QRect(0, 0, 68, 515))
        self.linien_graph_area.setObjectName("linien_graph_area")
        self.scrollArea_3.setWidget(self.linien_graph_area)
        self.linien_settings_frame = QtWidgets.QFrame(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.linien_settings_frame.sizePolicy().hasHeightForWidth())
        self.linien_settings_frame.setSizePolicy(sizePolicy)
        self.linien_settings_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.linien_settings_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.linien_settings_frame.setObjectName("linien_settings_frame")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.linien_settings_frame)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.linien_schleifen_check = QtWidgets.QCheckBox(self.linien_settings_frame)
        self.linien_schleifen_check.setObjectName("linien_schleifen_check")
        self.verticalLayout_8.addWidget(self.linien_schleifen_check)
        self.linien_check_2 = QtWidgets.QCheckBox(self.linien_settings_frame)
        self.linien_check_2.setObjectName("linien_check_2")
        self.verticalLayout_8.addWidget(self.linien_check_2)
        self.linien_check_3 = QtWidgets.QCheckBox(self.linien_settings_frame)
        self.linien_check_3.setObjectName("linien_check_3")
        self.verticalLayout_8.addWidget(self.linien_check_3)
        self.linien_aktualisieren_button = QtWidgets.QPushButton(self.linien_settings_frame)
        self.linien_aktualisieren_button.setObjectName("linien_aktualisieren_button")
        self.verticalLayout_8.addWidget(self.linien_aktualisieren_button)
        spacerItem2 = QtWidgets.QSpacerItem(20, 384, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem2)
        self.verticalLayout_9.addWidget(self.splitter_3)
        self.verticalLayout_10.addWidget(self.widget_3)
        self.tabWidget.addTab(self.linien_tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        GleisnetzWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(GleisnetzWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(GleisnetzWindow)

    def retranslateUi(self, GleisnetzWindow):
        _translate = QtCore.QCoreApplication.translate
        GleisnetzWindow.setWindowTitle(_translate("GleisnetzWindow", "Gleisnetz"))
        self.signal_weichen_check.setText(_translate("GleisnetzWindow", "Weichen entfernen"))
        self.signal_anschluss_check.setText(_translate("GleisnetzWindow", "Anschlüsse prüfen"))
        self.signal_bahnsteig_check.setText(_translate("GleisnetzWindow", "Ausfahrsignale entfernen"))
        self.signal_paar_check.setText(_translate("GleisnetzWindow", "Blocksignale entfernen"))
        self.signal_zwischen_check.setText(_translate("GleisnetzWindow", "Zwischensignale entfernen"))
        self.signal_schleifen_check.setText(_translate("GleisnetzWindow", "Schleifen auflösen"))
        self.signal_nachbarn_check.setText(_translate("GleisnetzWindow", "Nachbarbahnsteige vereinen"))
        self.signal_reserve1_check.setText(_translate("GleisnetzWindow", "(keine Funktion)"))
        self.signal_aktualisieren_button.setText(_translate("GleisnetzWindow", "Grafik aktualisieren"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.signal_tab), _translate("GleisnetzWindow", "Gleisplan"))
        self.bahnhof_leerverbindung_check.setText(_translate("GleisnetzWindow", "Leere Verbindungen"))
        self.bahnhof_check_1.setText(_translate("GleisnetzWindow", "Keine Funktion"))
        self.bahnhof_check_2.setText(_translate("GleisnetzWindow", "Keine Funktion"))
        self.bahnhof_check_3.setText(_translate("GleisnetzWindow", "Keine Funktion"))
        self.bahnhof_aktualisieren_button.setText(_translate("GleisnetzWindow", "Grafik aktualisieren"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.bahnhof_tab), _translate("GleisnetzWindow", "Bahnhofplan"))
        self.linien_schleifen_check.setText(_translate("GleisnetzWindow", "Schleifen auflösen"))
        self.linien_check_2.setText(_translate("GleisnetzWindow", "Keine Funktion"))
        self.linien_check_3.setText(_translate("GleisnetzWindow", "Keine Funktion"))
        self.linien_aktualisieren_button.setText(_translate("GleisnetzWindow", "Grafik aktualisieren"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.linien_tab), _translate("GleisnetzWindow", "Liniennetz"))

