@startuml
'https://plantuml.com/object-diagram

object Stammzug {
    Flügelung-Flag
    --
    Abfahrt wie Planhalt
}

object "Stammzug nächster Halt" as StammzugSucc

object Folgezug {
    Anschluss 1
    --
    an = Ankunft Stammzug
    ab = Abfahrt zweiter Zug
}
'Ankunftszeiten der beiden Züge sind gleich

object "Folgezug nächster Halt" as FolgezugSucc

object "Zubringerzug 1" as A1

object "Anschlusszug 2" as A2 {
Anschluss 2
}

object "Anschlusszug 3" as A3 {
Anschluss 3
}

Stammzug "t_an" --> "t_an" Folgezug: F
Stammzug "v_ab" --> "v_an" StammzugSucc: P
Folgezug --> FolgezugSucc: P

A1 "*" -[dashed]-> Folgezug: A
Folgezug -[dashed]-> "*" A2: A
Stammzug -[dashed]-> "*" A3: A

note "Flügeln" as N1

@enduml
