@startuml
'https://plantuml.com/object-diagram

object Stammzug {
    Kupplung-Flag
    --
    an = Ankunft erster Zug
    ab = Kupplungszeit
}
'Stammzug hat keine Abfahrtszeit

note left of Stammzug
Zug endet
end note

object "Stammzug vorheriger Halt" as StammzugPred

object Folgezug {
    Anschluss 1
    --
    an = Ankunft zweiter Zug
    ab = Kupplungszeit und Abfahrt
}

object "Folgezug vorheriger Halt" as FolgezugPred

object "Folgezug nächster Halt" as FolgezugSucc

object "Zubringerzug 1" as A1

object "Anschlusszug 2" as A2 {
Anschluss 2
}

object "Anschlusszug 3" as A3 {
Anschluss 3
}

StammzugPred --> Stammzug: P
Stammzug "t<sub>an</sub>" --> "t<sub>ab</sub>" Folgezug: K
Stammzug "t<sub>ab</sub>" <-[dotted]- "t<sub>an</sub>" Folgezug: !!!
FolgezugPred "v<sub>ab</sub>" --> "v<sub>an</sub>" Folgezug: P
Folgezug --> FolgezugSucc: P
FolgezugPred -[dotted]-> Stammzug: Reihenfolge?

A1 -[dashed]-> "t<sub>ab</sub>" Folgezug: A
Folgezug -[dashed]-> A2: A
Stammzug -[dashed]-> A3: A

note "Kuppeln" as N1

@enduml
