name: Build release

on:
  push:
    branches:
      - 'releases'

jobs:
  build:
     strategy:
        matrix:
          os: [ubuntu-latest, windows-latest]

     runs-on: ${{ matrix.os }}

     steps:
        - name: Check-out repository
          uses: actions/checkout@v4

        - name: Install uv
          uses: astral-sh/setup-uv@v5

        - name: Install the project
          run: uv sync --locked --all-extras --dev

        - name: Build Executable with Nuitka
          uses: Nuitka/Nuitka-Action@main
          with:
             nuitka-version: main
             script-name: stsdispo.py

        - name: Upload Artifacts
          uses: actions/upload-artifact@v4
          with:
             name: ${{ runner.os }} Build
             path: | # match what's created for the 3 OSes
                build/*.exe
                build/*.bin
                build/*.app/**/*
             include-hidden-files: true
